### PR TITLE
feat: add kaijun profolio

### PR DESCRIPTION
**Pull request by williron3960**
feat: add kaijun profolio.

### CODE REVIEW

**Comment by coliver0221** [comment]
You need to add your portfolios in `src/components/memberPage/members.json`.

**Comment by grandq33769** [comment]
NCKU_NetDB_Lab

I think the avatar don't look good. Your head is cut off.... Would you please change another avatar ?

**Comment by williron3960** [comment]
> NCKU_NetDB_Lab
> 
> I think the avatar don't look good. Your head is cut off.... Would you please change another avatar ?

**Comment by williron3960** [comment]
Thanks, I updated my personal photo.

**Review by grandq33769 — APPROVED** [review]
LGTM

**Pull request merged**
